### ISSUE TITLE
Wrong parsing withRequiredArg

### ISSUE THREAD

**Issue by imhy** [jopt-simple/jopt-simple#139]
Hi, all!
My parser configuration:
OptionParser parser = new OptionParser(false);
parser.accepts("aopt").withRequiredArg().required();
parser.accepts("bopt").withRequiredArg().required();

When I try prse:
parser.parse("--aopt", "--bopt", "2");

I get error:
joptsimple.MissingRequiredOptionsException: Missing required option(s) [bopt]

But it is must be missing argument for aopt.

**Comment by rsbreidenbach** [comment]
While this might be a confusing message, this is accurate because `--bopt` is consumed as the option for `--aopt`. This is the same behaviour in the `getopt` shell library. Given this script:

```
#!/bin/bash

while getopts "a:b:" arg; do
  case $arg in
    a)
      echo "option 'a' called with $OPTARG" 
      ;;
    b)
      echo "option 'b' called with $OPTARG" 
      ;;
  esac
done
```

This is the behavior:

```
% ./getops.sh -a -b bar
option 'a' called with -b
```

As you can see `-b` is interpreted as the option to `-a`. Since jopt-simple tries to emulate the behavior of `getopt`, I am inclined not to change any behavior.
